server:
<<<<<<< HEAD
  port: 8080

# jinwoo Database와 게시판 연결
# user사용자 / UserPassword 사용자 비밀번호
=======
  port: 8082
>>>>>>> feature/ExceptionError

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test
=======
    url: jdbc:mysql://localhost:3306/db_test1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test1
>>>>>>> feature/ExceptionError
    password: 1234
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update